### ISSUE TITLE
Missing XK

### ISSUE THREAD

**Issue by nick-adjust** [adjust/pg-country#12]
Citing @van-mronov 's email:
```
Hi all,

I'm working on implementing Facebook country grouping of cost data (https://adjustcom.atlassian.net/browse/ADAPP-3627).
I noticed that we don't have Kosovo (country code: XK) In our country list, but Facebook reports it sometimes.
Our kpi_external_agg Postgres DB replies with the following error when I try to insert record with `XK` as country:
%{code: :internal_error, file: "country.c", line: "271", message: "invalid country input string XK", pg_code: "XX000", routine: "country_from_str", severity: "ERROR", unknown: "ERROR"}, query: nil}

This comes from pg-country extension.

So, here is my question.
Should we add Kosovo? Or should we attribute those rows to 'Unknown country'?

Here are my concerns and pitfalls I see:
- Adding Kosovo will cause changes at least in pg-country and Dashboard. I don't know if any other services are affected and should be updated;
- I'm not sure if Kosovo is the only one country reported by Facebook which we do not have support for;
- On the other hand, attribution to Unknown may cause questions from clients.

Ivan Mironov
```

**Comment by rapimo** [comment]
https://github.com/adjust/pg-country/blob/fb190dcc8c5b272ded9ecd2679196e586a4a280f/src/country.c#L267

Keep in mind that this would need separate sorting facilities. 

Also XK is not an official iso 3166-1 Code but a user assigned code element (XA-XZ).

**Comment by van-mronov** [comment]
@rapimo thanks for your notes. So, it makes sense to attribute these cost records to 'Unknown' country, right?

**Comment by rapimo** [comment]
for now I'd vote for yes put it to `zz` 
Meanwhile I'll draft something to add `xk` but you should not make it as a blocker.
I'll assume that removing the mapping from `xk` to `zz` is only a single line for you that could be easily reverted once we support `xk`.
Let me know if this would be a problem for you then I can add a quick intermediate fix on the country extension to map `xk` to `zz` for you.

**Comment by van-mronov** [comment]
@rapimo thanks for your reply.
Yeah, it doesn't block me at all. I took the country list from the [countries.h](https://github.com/adjust/pg-country/blob/master/src/countries.h), so I can map any missing country to `zz`.

**Comment by rapimo** [comment]
FTR The only way to add `xk` without the need to build a special sorting algorithm and hence needing to rebuild all indexes that include country would be to jam it between `zw` and `zz` 

https://github.com/adjust/pg-country/blob/433e1cddebfd04a30f3a866e0135798963844e47/src/country.c#L271-L273

That would maybe look strange in a sorted result but could be argued that we put user assigned code elements behind the official ISO codes.
